# ========================================================================================
#  (C) (or copyright) 2023-2024. Triad National Security, LLC. All rights reserved.
#
#  This program was produced under U.S. Government contract 89233218CNA000001 for Los
#  Alamos National Laboratory (LANL), which is operated by Triad National Security, LLC
#  for the U.S. Department of Energy/National Nuclear Security Administration. All rights
#  in the program are reserved by Triad National Security, LLC, and the U.S. Department
#  of Energy/National Nuclear Security Administration. The Government is granted for
#  itself and others acting on its behalf a nonexclusive, paid-up, irrevocable worldwide
#  license in this material to reproduce, prepare derivative works, distribute copies to
#  the public, perform publicly and display publicly, and to permit others to do so.
# ========================================================================================

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - ci_doc
  - ci_format
  - ci_test
  - deploy

.default-job:
  tags:
    - darwin-slurm-shared
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://gitlab.lanl.gov

.default-ci-job:
  extends: .default-job
  rules:
    - if: '$CI_MERGE_REQUEST_TITLE =~ /Draft:/ || $CI_MERGE_REQUEST_TITLE =~ /WIP:/'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.default-nightly-job:
  extends: .default-job
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never

ci_format-job:
  extends: .default-ci-job
  stage: ci_format
  variables:
    SCHEDULER_PARAMETERS: "--nodes=1 --partition=skylake-gold --time=04:00:00"
  script:
    - cd $CI_PROJECT_DIR
    - source env/bash
    - VERBOSE=1 ./style/format.sh
    - git diff --exit-code --ignore-submodules

ci_cpu-job:
  extends: .default-ci-job
  stage: ci_test
  variables:
    SCHEDULER_PARAMETERS: "--nodes=1 --partition=skylake-gold --time=04:00:00"
  script:
    - cd $CI_PROJECT_DIR
    - source env/bash
    - cd $CI_PROJECT_DIR/tst
    - python3 run_tests.py
      regression.suite
      --save_build
      --make_nproc=32
      --cmake=-DCMAKE_C_COMPILER=gcc
      --cmake=-DCMAKE_CXX_COMPILER=g++
      --log_file=ci_cpu_log.txt
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - tst/ci_cpu_log.txt
      - tst/figs

ci_gpu-job:
  extends: .default-ci-job
  stage: ci_test
  variables:
    SCHEDULER_PARAMETERS: "--nodes=1 --partition=volta-x86 --time=04:00:00"
  script:
    - cd $CI_PROJECT_DIR
    - source env/bash
    - cd $CI_PROJECT_DIR/tst
    - python3 run_tests.py
      gpu.suite
      --save_build
      --make_nproc=32
      --cmake=-DARTEMIS_ENABLE_CUDA=On
      --cmake=-DKokkos_ARCH_VOLTA70=On
      --cmake=-DCMAKE_CXX_COMPILER=$CI_PROJECT_DIR/external/parthenon/external/Kokkos/bin/nvcc_wrapper
      --log_file=ci_gpu_log.txt
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - tst/ci_gpu_log.txt
      - tst/figs

ci_nightly-cpu-job:
  extends: .default-nightly-job
  stage: ci_test
  variables:
    SCHEDULER_PARAMETERS: "--nodes=1 --partition=skylake-gold --time=08:00:00"
  script:
    - cd $CI_PROJECT_DIR
    - cd external/parthenon
    - git pull origin develop
    - echo "==> Current Parthenon commit hash:"
    - git rev-parse HEAD
    - cd ../../
    - source env/bash
    - cd $CI_PROJECT_DIR/tst
    - python3 run_tests.py
      regression.suite
      --make_nproc=32
      --cmake=-DCMAKE_C_COMPILER=gcc
      --cmake=-DCMAKE_CXX_COMPILER=g++
      --log_file=ci_cpu_log.txt
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - tst/ci_cpu_log.txt
      - tst/figs

ci_nightly-gpu-job:
  extends: .default-nightly-job
  stage: ci_test
  variables:
    SCHEDULER_PARAMETERS: "--nodes=1 --partition=volta-x86 --time=08:00:00"
  script:
    - cd $CI_PROJECT_DIR
    - cd external/parthenon
    - git pull origin develop
    - echo "==> Current Parthenon commit hash:"
    - git rev-parse HEAD
    - cd ../../
    - source env/bash
    - cd $CI_PROJECT_DIR/tst
    - python3 run_tests.py
      gpu.suite
      --save_build
      --make_nproc=32
      --make_nproc=32
      --cmake=-DARTEMIS_ENABLE_CUDA=On
      --cmake=-DKokkos_ARCH_VOLTA70=On
      --cmake=-DCMAKE_CXX_COMPILER=$CI_PROJECT_DIR/external/parthenon/external/Kokkos/bin/nvcc_wrapper
      --log_file=ci_gpu_log.txt
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - tst/ci_gpu_log.txt
      - tst/figs


ci-doc-job:
  extends: .default-ci-job
  image: python:latest
  stage: ci_doc
  script:
  - cd $CI_PROJECT_DIR/doc
  - pip install -U sphinx-rtd-theme
  - pip install -U pyyaml
  - sphinx-build -b html . ../public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH


pages:
  extends: .default-job
  image: python:latest
  stage: deploy
  script:
  - cd $CI_PROJECT_DIR/doc
  - pip install -U sphinx-rtd-theme
  - pip install -U pyyaml
  - sphinx-build -b html . ../public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
